# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-wait-commit-status
  description: Wait Github Commit Status
  homepage: https://cloudposse.com/accelerate
  topics: ""
