name: 'Wait commit status'
description: 'Checks GitHub API for a given commit and look the commit status'
author: hello@cloudposse.com
branding:
  icon: 'clock'
  color: 'white'
inputs:
  check-retry-count:
    description: 'Check retry count'
    required: false
    default: "5"
  check-retry-interval:
    description: 'Check retry interval (in seconds)'
    required: false
    default: "10"
  token:
    description: 'Github authentication token'
    required: false
    default: ${{ github.token }}
  repository:
    required: true
    description: "Repository"
  sha:
    required: true
    description: "Commit SHA"
  status:
    required: true
    description: "Commit status name"
  expected_state:
    required: false
    description: "Commit status state wait for. Valid values 'success', 'error', 'failure', 'pending'"
    default: "success"
runs:
  using: "node16"
  main: "index.js"

