name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  check-timeout:
    required: true
    description: "Input parameter placeholder"
    default: "true"
  check-retry-count:
    required: true
    description: "Input parameter placeholder"
    default: "true"
  check-retry-interval:
    required: true
    description: "Input parameter placeholder"
    default: "true"
  repository:
    required: true
    description: "Input parameter placeholder"
    default: "true"
  ref:
    required: true
    description: "Input parameter placeholder"
    default: "true"
  status:
    required: true
    description: "Input parameter placeholder"
    default: "true"
  lookup:
    required: true
    description: "Input parameter placeholder"
    default: "true"
runs:
  using: "node16"
  main: "index.js"

